//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Collections.Specialized;
using System.ComponentModel;
using System.Globalization;
using System.Runtime.Serialization;

namespace CrossCutting.Mietmaschinendatenbank_DataClasses
{
    [DataContract(IsReference = true)]
    [KnownType(typeof(Vermietung))]
    public partial class Kunde: IObjectWithChangeTracker, INotifyPropertyChanged
    {
        #region Simple Properties
    
        [DataMember]
        public int Kunden_ID
        {
            get { return _kunden_ID; }
            set
            {
                if (_kunden_ID != value)
                {
                    if (ChangeTracker.ChangeTrackingEnabled && ChangeTracker.State != ObjectState.Added)
                    {
                        throw new InvalidOperationException("The property 'Kunden_ID' is part of the object's key and cannot be changed. Changes to key properties can only be made when the object is not being tracked or is in the Added state.");
                    }
                    _kunden_ID = value;
                    OnPropertyChanged("Kunden_ID");
                }
            }
        }
        private int _kunden_ID;
    
        [DataMember]
        public string Kundenname
        {
            get { return _kundenname; }
            set
            {
                if (_kundenname != value)
                {
                    _kundenname = value;
                    OnPropertyChanged("Kundenname");
                }
            }
        }
        private string _kundenname;
    
        [DataMember]
        public double Kundengesamtumsatz
        {
            get { return _kundengesamtumsatz; }
            set
            {
                if (_kundengesamtumsatz != value)
                {
                    _kundengesamtumsatz = value;
                    OnPropertyChanged("Kundengesamtumsatz");
                }
            }
        }
        private double _kundengesamtumsatz;

        #endregion

        #region Navigation Properties
    
        [DataMember]
        public TrackableCollection<Vermietung> Vermietung
        {
            get
            {
                if (_vermietung == null)
                {
                    _vermietung = new TrackableCollection<Vermietung>();
                    _vermietung.CollectionChanged += FixupVermietung;
                }
                return _vermietung;
            }
            set
            {
                if (!ReferenceEquals(_vermietung, value))
                {
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        throw new InvalidOperationException("Cannot set the FixupChangeTrackingCollection when ChangeTracking is enabled");
                    }
                    if (_vermietung != null)
                    {
                        _vermietung.CollectionChanged -= FixupVermietung;
                    }
                    _vermietung = value;
                    if (_vermietung != null)
                    {
                        _vermietung.CollectionChanged += FixupVermietung;
                    }
                    OnNavigationPropertyChanged("Vermietung");
                }
            }
        }
        private TrackableCollection<Vermietung> _vermietung;

        #endregion

        #region ChangeTracking
    
        protected virtual void OnPropertyChanged(String propertyName)
        {
            if (ChangeTracker.State != ObjectState.Added && ChangeTracker.State != ObjectState.Deleted)
            {
                ChangeTracker.State = ObjectState.Modified;
            }
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        protected virtual void OnNavigationPropertyChanged(String propertyName)
        {
            if (_propertyChanged != null)
            {
                _propertyChanged(this, new PropertyChangedEventArgs(propertyName));
            }
        }
    
        event PropertyChangedEventHandler INotifyPropertyChanged.PropertyChanged{ add { _propertyChanged += value; } remove { _propertyChanged -= value; } }
        private event PropertyChangedEventHandler _propertyChanged;
        private ObjectChangeTracker _changeTracker;
    
        [DataMember]
        public ObjectChangeTracker ChangeTracker
        {
            get
            {
                if (_changeTracker == null)
                {
                    _changeTracker = new ObjectChangeTracker();
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
                return _changeTracker;
            }
            set
            {
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging -= HandleObjectStateChanging;
                }
                _changeTracker = value;
                if(_changeTracker != null)
                {
                    _changeTracker.ObjectStateChanging += HandleObjectStateChanging;
                }
            }
        }
    
        private void HandleObjectStateChanging(object sender, ObjectStateChangingEventArgs e)
        {
            if (e.NewState == ObjectState.Deleted)
            {
                ClearNavigationProperties();
            }
        }
    
        protected bool IsDeserializing { get; private set; }
    
        [OnDeserializing]
        public void OnDeserializingMethod(StreamingContext context)
        {
            IsDeserializing = true;
        }
    
        [OnDeserialized]
        public void OnDeserializedMethod(StreamingContext context)
        {
            IsDeserializing = false;
            ChangeTracker.ChangeTrackingEnabled = true;
        }
    
        protected virtual void ClearNavigationProperties()
        {
            Vermietung.Clear();
        }

        #endregion

        #region Association Fixup
    
        private void FixupVermietung(object sender, NotifyCollectionChangedEventArgs e)
        {
            if (IsDeserializing)
            {
                return;
            }
    
            if (e.NewItems != null)
            {
                foreach (Vermietung item in e.NewItems)
                {
                    item.Kunde = this;
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        if (!item.ChangeTracker.ChangeTrackingEnabled)
                        {
                            item.StartTracking();
                        }
                        ChangeTracker.RecordAdditionToCollectionProperties("Vermietung", item);
                    }
                }
            }
    
            if (e.OldItems != null)
            {
                foreach (Vermietung item in e.OldItems)
                {
                    if (ReferenceEquals(item.Kunde, this))
                    {
                        item.Kunde = null;
                    }
                    if (ChangeTracker.ChangeTrackingEnabled)
                    {
                        ChangeTracker.RecordRemovalFromCollectionProperties("Vermietung", item);
                    }
                }
            }
        }

        #endregion

    }
}
